[package]
name = "pkmt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.15", features = ["derive"] }
edit-distance = "2.1.2"
logos = "0.14.1"
pathdiff = "0.2.1"
regex = "1.10.6"
